site_name: Od-Metrics

theme:
  name: "material"
  palette:
    scheme: slate
    primary: amber
  logo: assets/images/logo_small.svg
  favicon: assets/images/logo_small_orange.svg
  features:
    - content.code.copy
    - content.code.select
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
 
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
  - search
  - bibtex:
      bib_file: bib.bib
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - mdx_math
  - toc:
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
extra_css:
  - assets/stylesheets/custom.css
repo_name: OD-Metrics
repo_url: https://github.com/EMalagoli92/OD-metrics
nav:
  - Get Started: index.md
  - Metrics:
      IoU: iou.md
      mAP: map.md
  - Usage: usage.md
  - API Reference: api_reference.md
